name: "Setup flatc"
description: "Download and install flatc binary"
inputs:
  flatc_version:
    description: "Version of the flatc binary"
    default: "25.12.19"
runs:
  using: "composite"
  steps:
    - name: Download flatc
      id: download-flatc
      shell: bash
      run: |
        wget -O /tmp/flatc.zip "https://github.com/google/flatbuffers/releases/download/v${{ inputs.flatc_version }}/Linux.flatc.binary.clang++-18.zip"
        unzip -o /tmp/flatc.zip flatc -d /tmp

        # This sometimes runs in a container where user is root and there's no sudo.
        if command -v sudo &>/dev/null
        then
          CMD=sudo
        else
          CMD=
        fi
        $CMD mv /tmp/flatc /usr/local/bin/

        rm -f /tmp/flatc.zip
        flatc --version
